<?php
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1356, 'pp_display_menu', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1357, 'pp_enable_right_click', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1358, 'pp_right_click_text', 'You can enable/disable right click protection using theme admin', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1360, 'pp_enable_responsive', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1361, 'pp_font', 'Open+Sans', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1362, 'pp_h1_size', '40', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1363, 'pp_h2_size', '32', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1364, 'pp_h3_size', '26', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1365, 'pp_h4_size', '22', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1366, 'pp_h5_size', '18', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1367, 'pp_h6_size', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1368, 'pp_menu_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1369, 'pp_submenu_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1370, 'pp_image_title_font_size', '62', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1371, 'pp_font_color', '#ebebeb', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1372, 'pp_content_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1373, 'pp_content_opacity_color', '70', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1374, 'pp_link_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1375, 'pp_hover_link_color', '#e64946', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1376, 'pp_h1_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1377, 'pp_button_bg_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1378, 'pp_button_font_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1379, 'pp_button_border_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1380, 'pp_menu_font_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1381, 'pp_menu_bg_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1382, 'pp_submenu_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1383, 'pp_submenu_bg_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1384, 'pp_submenu_hover_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1385, 'pp_submenu_hover_bg_color', '#e64946', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1386, 'pp_menu_epcls_bg_color', '#e64946', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1387, 'pp_homepage_style', 'fullscreen', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1390, 'pp_homepage_youtube_id', '5pEbJpjxbbU', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1391, 'pp_homepage_vimeo_id', '58363796', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1392, 'pp_portfolio_autoplay', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1393, 'pp_portfolio_slideshow_timer', '4', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1394, 'pp_portfolio_slideshow_trans', '1', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1396, 'pp_portfolio_enable_slideshow_title', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1429, 'pp_portfolio_enable_bg_overlay', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1397, 'pp_enable_reflection', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1398, 'pp_set_page_template', '2', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1399, 'pp_youtube_video_ratio', '16/9', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1402, 'pp_contact_form', 's:8:\"s:1:\"1\";\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1403, 'pp_contact_display_map', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1404, 'pp_contact_lat', '40.724755', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1405, 'pp_contact_long', '-74.0107', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1406, 'pp_contact_map_zoom', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1407, 'pp_contact_info_box', 'Our Photography Studio', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1408, 'pp_facebook_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1409, 'pp_twitter_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1410, 'pp_google_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1411, 'pp_flickr_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1412, 'pp_youtube_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1413, 'pp_vimeo_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1414, 'pp_tumblr_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1415, 'pp_digg_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1416, 'pp_dribbble_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1417, 'pp_linkedin_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1418, 'pp_pinterest_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1419, 'pp_footer_display_sidebar', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1420, 'pp_footer_style', '3', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1421, 'pp_footer_text', '© 2013 Keres Theme', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1424, 'pp_font_family', 'Open Sans', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(1428, 'pp_contact_form_sort_data', 's:42:\"a:3:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";}\";', 'yes');");
?>